CREATE DATABASE `bookmanager` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE BOOKMANAGER.BOOK (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME_BOOK VARCHAR(255) NOT NULL,
  BOOK_TITLE VARCHAR(255) NOT NULL,
  BOOK_AUTHOR VARCHAR(255) NOT NULL,
  BOOK_PRICE INT NOT NULL,
  PRIMARY KEY (ID));

CREATE TABLE BOOKMANAGER.AUTHOR (
  ID INT NOT NULL AUTO_INCREMENT,
  AUTHOR_NAME VARCHAR(255) NOT NULL,
  BOOK_AUTHOR VARCHAR(255) NOT NULL,
  DISCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID));

